


pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = "sarvnoorkaur"
        BACKEND_IMAGE = "collabsphere-backend"
        FRONTEND_IMAGE = "collabsphere-frontend"
        K8S_SERVER = "172.31.21.141"  // Get from: terraform output k8s_private_ip
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Sarvnoor-kaur/Collab.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build -t $DOCKER_HUB_REPO/$BACKEND_IMAGE:latest \
                -f docker/backend.Dockerfile ./backend
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker build -t $DOCKER_HUB_REPO/$FRONTEND_IMAGE:latest \
                -f docker/frontend.Dockerfile ./client
                '''
            }
        }

        stage('Push Images to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin

                    docker push $DOCKER_HUB_REPO/$BACKEND_IMAGE:latest
                    docker push $DOCKER_HUB_REPO/$FRONTEND_IMAGE:latest

                    docker logout
                    '''
                }
            }
        }

        stage('Deploy to K3s') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@$K8S_SERVER "

                    cd ~/Collab &&

                    git pull &&

                    sudo kubectl apply -f k8s/

                    sudo kubectl rollout restart deployment/backend -n collabsphere

                    sudo kubectl rollout restart deployment/frontend -n collabsphere

                    sudo kubectl get pods -n collabsphere
                "
                '''
            }
        }

    }

    post {
        success {
            echo '✅ Deployment Successful!'
        }

        failure {
            echo '❌ Deployment Failed!'
        }
    }
}
